# Generated by Django 5.0.3 on 2024-05-05 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0013_tag_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('idPost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DjangoApp.post')),
                ('idUsercomment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DjangoApp.userinfo')),
                ('idcommentReply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DjangoApp.comment')),
            ],
        ),
    ]
