# Generated by Django 5.0.3 on 2024-05-05 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0014_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('star', models.IntegerField(default=0)),
                ('idpost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DjangoApp.post')),
                ('iduser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DjangoApp.userinfo')),
            ],
        ),
    ]
