# Generated by Django 5.0.3 on 2024-05-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0015_react'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='numcreact',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='totalstar',
            field=models.IntegerField(default=0),
        ),
    ]
