# Generated by Django 5.0.3 on 2024-05-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0017_historychat'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='lng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
