# Generated by Django 5.0.3 on 2024-05-11 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0018_alter_post_image'),
        ('DjangoApp', '0018_post_lat_post_lng'),
    ]

    operations = [
    ]
